import os
import json
import secrets

from nltk.corpus import stopwords

BASE_PATH = os.environ.get("BASE_PATH", "C:\\Projects\\Python_projects\\Covid19_Analysis")

TABLE_NAME = "covid"
TRENDING_TABLE_NAME = "trending"
POS_NEG_NEUT = 0.1

TABLE_ATTRIBUTES = {
    "base": """
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp_ms INTEGER,
    tweet TEXT,
    created_at TEXT,
    user_location TEXT,
    user_name TEXT,
    screen_name TEXT,
    verified BOOLEAN,
    sentiment REAL
    """
}

APP_COLORS = {
    'background': '#F0F0F7',
    'text': '#000000',
    'sentiment-plot': '#41EAD4',
    'volume-bar': '#FBFC74',
    'someothercolor': '#9cc0e7',
}

SENTIMENT_COLORS = {
    -1: "#EE6055",
    -0.5: "#FDE74C",
    0: "#FFE6AC",
    0.5: "#D0F2DF",
    1: "#9CEC5B"
}

BASIC_STOP_WORDS = ['a',
                    'about',
                    'above',
                    'across',
                    'after',
                    'again',
                    'against',
                    'all',
                    'almost',
                    'alone',
                    'along',
                    'already',
                    'also',
                    'although',
                    'always',
                    'among',
                    'an',
                    'and',
                    'another',
                    'any',
                    'anybody',
                    'anyone',
                    'anything',
                    'anywhere',
                    'are',
                    'area',
                    'areas',
                    'around',
                    'as',
                    'ask',
                    'asked',
                    'asking',
                    'asks',
                    'at',
                    'away',
                    'b',
                    'back',
                    'backed',
                    'backing',
                    'backs',
                    'be',
                    'became',
                    'because',
                    'become',
                    'becomes',
                    'been',
                    'before',
                    'began',
                    'behind',
                    'being',
                    'beings',
                    'best',
                    'better',
                    'between',
                    'big',
                    'both',
                    'but',
                    'by',
                    'c',
                    'came',
                    'can',
                    'cannot',
                    'case',
                    'cases',
                    'certain',
                    'certainly',
                    'clear',
                    'clearly',
                    'come',
                    'could',
                    'd',
                    'did',
                    'differ',
                    'different',
                    'differently',
                    'do',
                    'does',
                    'done',
                    'down',
                    'down',
                    'downed',
                    'downing',
                    'downs',
                    'during',
                    'e',
                    'each',
                    'early',
                    'either',
                    'end',
                    'ended',
                    'ending',
                    'ends',
                    'enough',
                    'even',
                    'evenly',
                    'ever',
                    'every',
                    'everybody',
                    'everyone',
                    'everything',
                    'everywhere',
                    'f',
                    'face',
                    'faces',
                    'fact',
                    'facts',
                    'far',
                    'felt',
                    'few',
                    'find',
                    'finds',
                    'first',
                    'for',
                    'four',
                    'from',
                    'full',
                    'fully',
                    'further',
                    'furthered',
                    'furthering',
                    'furthers',
                    'g',
                    'gave',
                    'general',
                    'generally',
                    'get',
                    'gets',
                    'give',
                    'given',
                    'gives',
                    'go',
                    'going',
                    'good',
                    'goods',
                    'got',
                    'great',
                    'greater',
                    'greatest',
                    'group',
                    'grouped',
                    'grouping',
                    'groups',
                    'h',
                    'had',
                    'has',
                    'have',
                    'having',
                    'he',
                    'her',
                    'here',
                    'herself',
                    'high',
                    'high',
                    'high',
                    'higher',
                    'highest',
                    'him',
                    'himself',
                    'his',
                    'how',
                    'however',
                    'i',
                    'if',
                    'important',
                    'in',
                    'interest',
                    'interested',
                    'interesting',
                    'interests',
                    'into',
                    'is',
                    'it',
                    'its',
                    'itself',
                    'j',
                    'just',
                    'k',
                    'keep',
                    'keeps',
                    'kind',
                    'knew',
                    'know',
                    'known',
                    'knows',
                    'l',
                    'large',
                    'largely',
                    'last',
                    'later',
                    'latest',
                    'least',
                    'less',
                    'let',
                    'lets',
                    'like',
                    'likely',
                    'long',
                    'longer',
                    'longest',
                    'm',
                    'made',
                    'make',
                    'making',
                    'man',
                    'many',
                    'may',
                    'me',
                    'member',
                    'members',
                    'men',
                    'might',
                    'more',
                    'most',
                    'mostly',
                    'mr',
                    'mrs',
                    'much',
                    'must',
                    'my',
                    'myself',
                    'n',
                    'necessary',
                    'need',
                    'needed',
                    'needing',
                    'needs',
                    'never',
                    'new',
                    'new',
                    'newer',
                    'newest',
                    'next',
                    'no',
                    'nobody',
                    'non',
                    'noone',
                    'not',
                    'nothing',
                    'now',
                    'nowhere',
                    'number',
                    'numbers',
                    'o',
                    'of',
                    'off',
                    'often',
                    'old',
                    'older',
                    'oldest',
                    'on',
                    'once',
                    'one',
                    'only',
                    'open',
                    'opened',
                    'opening',
                    'opens',
                    'or',
                    'order',
                    'ordered',
                    'ordering',
                    'orders',
                    'other',
                    'others',
                    'our',
                    'out',
                    'over',
                    'p',
                    'part',
                    'parted',
                    'parting',
                    'parts',
                    'per',
                    'perhaps',
                    'place',
                    'places',
                    'point',
                    'pointed',
                    'pointing',
                    'points',
                    'possible',
                    'present',
                    'presented',
                    'presenting',
                    'presents',
                    'problem',
                    'problems',
                    'put',
                    'puts',
                    'q',
                    'quite',
                    'r',
                    'rather',
                    'really',
                    'right',
                    'right',
                    'room',
                    'rooms',
                    's',
                    'said',
                    'same',
                    'saw',
                    'say',
                    'says',
                    'second',
                    'seconds',
                    'see',
                    'seem',
                    'seemed',
                    'seeming',
                    'seems',
                    'sees',
                    'several',
                    'shall',
                    'she',
                    'should',
                    'show',
                    'showed',
                    'showing',
                    'shows',
                    'side',
                    'sides',
                    'since',
                    'small',
                    'smaller',
                    'smallest',
                    'so',
                    'some',
                    'somebody',
                    'someone',
                    'something',
                    'somewhere',
                    'state',
                    'states',
                    'still',
                    'still',
                    'such',
                    'sure',
                    't',
                    'take',
                    'taken',
                    'than',
                    'that',
                    'the',
                    'their',
                    'them',
                    'then',
                    'there',
                    'therefore',
                    'these',
                    'they',
                    'thing',
                    'things',
                    'think',
                    'thinks',
                    'this',
                    'those',
                    'though',
                    'thought',
                    'thoughts',
                    'three',
                    'through',
                    'thus',
                    'to',
                    'today',
                    'together',
                    'too',
                    'took',
                    'toward',
                    'turn',
                    'turned',
                    'turning',
                    'turns',
                    'two',
                    'u',
                    'under',
                    'until',
                    'up',
                    'upon',
                    'us',
                    'use',
                    'used',
                    'uses',
                    'v',
                    'very',
                    'w',
                    'want',
                    'wanted',
                    'wanting',
                    'wants',
                    'was',
                    'way',
                    'ways',
                    'we',
                    'well',
                    'wells',
                    'went',
                    'were',
                    'what',
                    'when',
                    'where',
                    'whether',
                    'which',
                    'while',
                    'who',
                    'whole',
                    'whose',
                    'why',
                    'will',
                    'with',
                    'within',
                    'without',
                    'work',
                    'worked',
                    'working',
                    'works',
                    'would',
                    'x',
                    'y',
                    'year',
                    'years',
                    'yet',
                    'you',
                    'young',
                    'younger',
                    'youngest',
                    'your',
                    'yours',
                    'z']

STOP_WORDS = ['', 'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'covid', '19', 'corona', 'please',
              'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him',
              'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its',
              'itself', 'they', 'them', 'their', 'theirs', 'themselves',
              'what', 'which', 'who', 'whom', 'this', 'that', 'these',
              'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'please'
                                                                       'being', 'have', 'has', 'had', 'having', 'do',
              'does', 'did',
              'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because',
              'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about',
              'against', 'between', 'into', 'through', 'during', 'before', 'after',
              'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on',
              'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here',
              'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each',
              'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not',
              'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can',
              'will', 'just', 'don', 'should', 'now', 'https', "'s", '...', "whats'",
              "rt", "whats", "n't", "de", "'m", "un", "en", "``", "dedic", "twittermoments",
              "amp", "e", "y", "o", "ce", "retweet", "sur", "na", "el", "1", "2", "3", "4",
              "5", "6", "7", "8", "9", "0", "ca", "nao", "se", "com", "los", "u", "des", "-",
              "--", "'", "''", "la", "como", "con", "segundo", 'de', 'la', 'que', 'el',
              'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para',
              'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus',
              'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando',
              'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde',
              'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les',
              'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto',
              'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras',
              'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada',
              'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo',
              'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas',
              'nosotras', 'vosostros', 'vosostras', 'os', 'mío', 'mía', 'míos',
              'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos',
              'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro',
              'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás',
              'está', 'estamos', 'estáis', 'están', 'esté', 'estés', 'estemos',
              'estéis', 'estén', 'estaré', 'estarás', 'estará', 'estaremos',
              'estaréis', 'estarán', 'estaría', 'estarías', 'estaríamos',
              'estaríais', 'estarían', 'estaba', 'estabas', 'estábamos',
              'estabais', 'estaban', 'estuve', 'estuviste', 'estuvo', 'estuvimos',
              'estuvisteis', 'estuvieron', 'estuviera', 'estuvieras', 'estuviéramos',
              'estuvierais', 'estuvieran', 'estuviese', 'estuvieses', 'estuviésemos',
              'estuvieseis', 'estuviesen', 'estando', 'estado', 'estada', 'estados',
              'estadas', 'estad', 'he', 'has', 'ha', 'hemos', 'habéis', 'han', 'haya',
              'hayas', 'hayamos', 'hayáis', 'hayan', 'habré', 'habrás', 'habrá', 'habremos',
              'habréis', 'habrán', 'habría', 'habrías', 'habríamos', 'habríais', 'habrían',
              'había', 'habías', 'habíamos', 'habíais', 'habían', 'hube', 'hubiste', 'hubo',
              'hubimos', 'hubisteis', 'hubieron', 'hubiera', 'hubieras', 'hubiéramos',
              'hubierais', 'hubieran', 'hubiese', 'hubieses', 'hubiésemos', 'hubieseis',
              'hubiesen', 'habiendo', 'habido', 'habida', 'habidos', 'habidas', 'soy',
              'eres', 'es', 'somos', 'sois', 'son', 'sea', 'seas', 'seamos', 'seáis',
              'sean', 'seré', 'serás', 'será', 'seremos', 'seréis', 'serán', 'sería',
              'serías', 'seríamos', 'seríais', 'serían', 'era', 'eras', 'éramos', 'erais',
              'eran', 'fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron', 'fuera',
              'fueras', 'fuéramos', 'fuerais', 'fueran', 'fuese', 'fueses', 'fuésemos',
              'fueseis', 'fuesen', 'sintiendo', 'sentido', 'sentida', 'sentidos',
              'sentidas', 'siente', 'sentid', 'tengo', 'tienes', 'tiene', 'tenemos',
              'tenéis', 'tienen', 'tenga', 'tengas', 'tengamos', 'tengáis', 'tengan',
              'tendré', 'tendrás', 'tendrá', 'tendremos', 'tendréis', 'tendrán',
              'tendría', 'tendrías', 'tendríamos', 'tendríais', 'tendrían', 'tenía',
              'tenías', 'teníamos', 'teníais', 'tenían', 'tuve', 'tuviste', 'tuvo',
              'tuvimos', 'tuvisteis', 'tuvieron', 'tuviera', 'tuvieras', 'tuviéramos',
              'tuvierais', 'tuvieran', 'tuviese', 'tuvieses', 'tuviésemos', 'tuvieseis',
              'tuviesen', 'teniendo', 'tenido', 'tenida', 'tenidos', 'tenidas', 'tened',
              "ve", "dia", "algun", "ningun", "pregunta", "segunda", "bugun", "mas", "da",
              "alguna", "si", "bur", "bu", "icin", "bir", "um", "know", "mais", "pra", "time", "q", "em",
              "re", "11", "isnt", "wan", "ver", "like", "'re", "m", "'ve", "bec", "n", "twt", "kca", "c", "a",
              "b", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
              "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "new"] + BASIC_STOP_WORDS

COUNTRY_CODE = {'Afghanistan': 'AF',
                'Albania': 'AL',
                'Algeria': 'DZ',
                'American Samoa': 'AS',
                'Andorra': 'AD',
                'Angola': 'AO',
                'Anguilla': 'AI',
                'Antarctica': 'AQ',
                'Antigua and Barbuda': 'AG',
                'Argentina': 'AR',
                'Armenia': 'AM',
                'Aruba': 'AW',
                'Australia': 'AU',
                'Austria': 'AT',
                'Azerbaijan': 'AZ',
                'Bahamas': 'BS',
                'Bahrain': 'BH',
                'Bangladesh': 'BD',
                'Barbados': 'BB',
                'Belarus': 'BY',
                'Belgium': 'BE',
                'Belize': 'BZ',
                'Benin': 'BJ',
                'Bermuda': 'BM',
                'Bhutan': 'BT',
                'Bolivia, Plurinational State of': 'BO',
                'Bosnia and Herzegovina': 'BA',
                'Botswana': 'BW',
                'Bouvet Island': 'BV',
                'Brazil': 'BR',
                'British Indian Ocean Territory': 'IO',
                'Brunei Darussalam': 'BN',
                'Bulgaria': 'BG',
                'Burkina Faso': 'BF',
                'Burundi': 'BI',
                'Cambodia': 'KH',
                'Cameroon': 'CM',
                'Canada': 'CA',
                'Cape Verde': 'CV',
                'Cayman Islands': 'KY',
                'Central African Republic': 'CF',
                'Chad': 'TD',
                'Chile': 'CL',
                'Mainland China': 'CN',
                'Christmas Island': 'CX',
                'Cocos (Keeling) Islands': 'CC',
                'Colombia': 'CO',
                'Comoros': 'KM',
                'Congo': 'CG',
                'Congo, the Democratic Republic of the': 'CD',
                'Cook Islands': 'CK',
                'Costa Rica': 'CR',
                'Croatia': 'HR',
                'Cuba': 'CU',
                'Curaçao': 'CW',
                'Cyprus': 'CY',
                'Czech Republic': 'CZ',
                "Côte d'Ivoire": 'CI',
                'Denmark': 'DK',
                'Djibouti': 'DJ',
                'Dominica': 'DM',
                'Dominican Republic': 'DO',
                'Ecuador': 'EC',
                'Egypt': 'EG',
                'El Salvador': 'SV',
                'Equatorial Guinea': 'GQ',
                'Eritrea': 'ER',
                'Estonia': 'EE',
                'Ethiopia': 'ET',
                'Falkland Islands (Malvinas)': 'FK',
                'Faroe Islands': 'FO',
                'Fiji': 'FJ',
                'Finland': 'FI',
                'France': 'FR',
                'French Guiana': 'GF',
                'French Polynesia': 'PF',
                'French Southern Territories': 'TF',
                'Gabon': 'GA',
                'Gambia': 'GM',
                'Georgia': 'GE',
                'Germany': 'DE',
                'Ghana': 'GH',
                'Gibraltar': 'GI',
                'Greece': 'GR',
                'Greenland': 'GL',
                'Grenada': 'GD',
                'Guadeloupe': 'GP',
                'Guam': 'GU',
                'Guatemala': 'GT',
                'Guernsey': 'GG',
                'Guinea': 'GN',
                'Guinea-Bissau': 'GW',
                'Guyana': 'GY',
                'Haiti': 'HT',
                'Heard Island and McDonald Islands': 'HM',
                'Holy See (Vatican City State)': 'VA',
                'Honduras': 'HN',
                'Hong Kong': 'HK',
                'Hungary': 'HU',
                'ISO 3166-2:GB': '(.uk)',
                'Iceland': 'IS',
                'India': 'IN',
                'Indonesia': 'ID',
                'Iran, Islamic Republic of': 'IR',
                'Iraq': 'IQ',
                'Ireland': 'IE',
                'Isle of Man': 'IM',
                'Israel': 'IL',
                'Italy': 'IT',
                'Jamaica': 'JM',
                'Japan': 'JP',
                'Jersey': 'JE',
                'Jordan': 'JO',
                'Kazakhstan': 'KZ',
                'Kenya': 'KE',
                'Kiribati': 'KI',
                "Korea, Democratic People's Republic of": 'KP',
                'South Korea': 'KR',
                'Kuwait': 'KW',
                'Kyrgyzstan': 'KG',
                "Lao People's Democratic Republic": 'LA',
                'Latvia': 'LV',
                'Lebanon': 'LB',
                'Lesotho': 'LS',
                'Liberia': 'LR',
                'Libya': 'LY',
                'Liechtenstein': 'LI',
                'Lithuania': 'LT',
                'Luxembourg': 'LU',
                'Macau': 'MO',
                'Macedonia, the former Yugoslav Republic of': 'MK',
                'Madagascar': 'MG',
                'Malawi': 'MW',
                'Malaysia': 'MY',
                'Maldives': 'MV',
                'Mali': 'ML',
                'Malta': 'MT',
                'Marshall Islands': 'MH',
                'Martinique': 'MQ',
                'Mauritania': 'MR',
                'Mauritius': 'MU',
                'Mayotte': 'YT',
                'Mexico': 'MX',
                'Micronesia, Federated States of': 'FM',
                'Moldova, Republic of': 'MD',
                'Monaco': 'MC',
                'Mongolia': 'MN',
                'Montenegro': 'ME',
                'Montserrat': 'MS',
                'Morocco': 'MA',
                'Mozambique': 'MZ',
                'Myanmar': 'MM',
                'Namibia': 'NA',
                'Nauru': 'NR',
                'Nepal': 'NP',
                'Netherlands': 'NL',
                'New Caledonia': 'NC',
                'New Zealand': 'NZ',
                'Nicaragua': 'NI',
                'Niger': 'NE',
                'Nigeria': 'NG',
                'Niue': 'NU',
                'Norfolk Island': 'NF',
                'Northern Mariana Islands': 'MP',
                'Norway': 'NO',
                'Oman': 'OM',
                'Pakistan': 'PK',
                'Palau': 'PW',
                'Palestine, State of': 'PS',
                'Panama': 'PA',
                'Papua New Guinea': 'PG',
                'Paraguay': 'PY',
                'Peru': 'PE',
                'Philippines': 'PH',
                'Pitcairn': 'PN',
                'Poland': 'PL',
                'Portugal': 'PT',
                'Puerto Rico': 'PR',
                'Qatar': 'QA',
                'Romania': 'RO',
                'Russia': 'RU',
                'Rwanda': 'RW',
                'Réunion': 'RE',
                'Saint Barthélemy': 'BL',
                'Saint Helena, Ascension and Tristan da Cunha': 'SH',
                'Saint Kitts and Nevis': 'KN',
                'Saint Lucia': 'LC',
                'Saint Martin (French part)': 'MF',
                'Saint Pierre and Miquelon': 'PM',
                'Saint Vincent and the Grenadines': 'VC',
                'Samoa': 'WS',
                'San Marino': 'SM',
                'Sao Tome and Principe': 'ST',
                'Saudi Arabia': 'SA',
                'Senegal': 'SN',
                'Serbia': 'RS',
                'Seychelles': 'SC',
                'Sierra Leone': 'SL',
                'Singapore': 'SG',
                'Sint Maarten (Dutch part)': 'SX',
                'Slovakia': 'SK',
                'Slovenia': 'SI',
                'Solomon Islands': 'SB',
                'Somalia': 'SO',
                'South Africa': 'ZA',
                'South Georgia and the South Sandwich Islands': 'GS',
                'South Sudan': 'SS',
                'Spain': 'ES',
                'Sri Lanka': 'LK',
                'Sudan': 'SD',
                'Suriname': 'SR',
                'Svalbard and Jan Mayen': 'SJ',
                'Swaziland': 'SZ',
                'Sweden': 'SE',
                'Switzerland': 'CH',
                'Syria': 'SY',
                'Taiwan': 'TW',
                'Tajikistan': 'TJ',
                'Tanzania': 'TZ',
                'Thailand': 'TH',
                'Timor-Leste': 'TL',
                'Togo': 'TG',
                'Tokelau': 'TK',
                'Tonga': 'TO',
                'Trinidad and Tobago': 'TT',
                'Tunisia': 'TN',
                'Turkey': 'TR',
                'Turkmenistan': 'TM',
                'Turks and Caicos Islands': 'TC',
                'Tuvalu': 'TV',
                'Uganda': 'UG',
                'Ukraine': 'UA',
                'United Arab Emirates': 'AE',
                'UK': 'GB',
                'US': 'US',
                'United States Minor Outlying Islands': 'UM',
                'Uruguay': 'UY',
                'Uzbekistan': 'UZ',
                'Vanuatu': 'VU',
                'Venezuela': 'VE',
                'Vietnam': 'VN',
                'Virgin Islands, British': 'VG',
                'Virgin Islands, U.S.': 'VI',
                'Wallis and Futuna': 'WF',
                'Western Sahara': 'EH',
                'Yemen': 'YE',
                'Zambia': 'ZM',
                'Zimbabwe': 'ZW',
                'Åland Islands': 'AX',
                'Ivory Coast': "CIV"}

convert_ISO_3166_2_to_1 = {
    'AF': 'AFG',
    'AX': 'ALA',
    'AL': 'ALB',
    'DZ': 'DZA',
    'AS': 'ASM',
    'AD': 'AND',
    'AO': 'AGO',
    'AI': 'AIA',
    'AQ': 'ATA',
    'AG': 'ATG',
    'AR': 'ARG',
    'AM': 'ARM',
    'AW': 'ABW',
    'AU': 'AUS',
    'AT': 'AUT',
    'AZ': 'AZE',
    'BS': 'BHS',
    'BH': 'BHR',
    'BD': 'BGD',
    'BB': 'BRB',
    'BY': 'BLR',
    'BE': 'BEL',
    'BZ': 'BLZ',
    'BJ': 'BEN',
    'BM': 'BMU',
    'BT': 'BTN',
    'BO': 'BOL',
    'BA': 'BIH',
    'BW': 'BWA',
    'BV': 'BVT',
    'BR': 'BRA',
    'IO': 'IOT',
    'BN': 'BRN',
    'BG': 'BGR',
    'BF': 'BFA',
    'BI': 'BDI',
    'KH': 'KHM',
    'CM': 'CMR',
    'CA': 'CAN',
    'CV': 'CPV',
    'KY': 'CYM',
    'CF': 'CAF',
    'TD': 'TCD',
    'CL': 'CHL',
    'CN': 'CHN',
    'CX': 'CXR',
    'CC': 'CCK',
    'CO': 'COL',
    'KM': 'COM',
    'CG': 'COG',
    'CD': 'COD',
    'CK': 'COK',
    'CR': 'CRI',
    'CI': 'CIV',
    'HR': 'HRV',
    'CU': 'CUB',
    'CY': 'CYP',
    'CZ': 'CZE',
    'DK': 'DNK',
    'DJ': 'DJI',
    'DM': 'DMA',
    'DO': 'DOM',
    'EC': 'ECU',
    'EG': 'EGY',
    'SV': 'SLV',
    'GQ': 'GNQ',
    'ER': 'ERI',
    'EE': 'EST',
    'ET': 'ETH',
    'FK': 'FLK',
    'FO': 'FRO',
    'FJ': 'FJI',
    'FI': 'FIN',
    'FR': 'FRA',
    'GF': 'GUF',
    'PF': 'PYF',
    'TF': 'ATF',
    'GA': 'GAB',
    'GM': 'GMB',
    'GE': 'GEO',
    'DE': 'DEU',
    'GH': 'GHA',
    'GI': 'GIB',
    'GR': 'GRC',
    'GL': 'GRL',
    'GD': 'GRD',
    'GP': 'GLP',
    'GU': 'GUM',
    'GT': 'GTM',
    'GG': 'GGY',
    'GN': 'GIN',
    'GW': 'GNB',
    'GY': 'GUY',
    'HT': 'HTI',
    'HM': 'HMD',
    'VA': 'VAT',
    'HN': 'HND',
    'HK': 'HKG',
    'HU': 'HUN',
    'IS': 'ISL',
    'IN': 'IND',
    'ID': 'IDN',
    'IR': 'IRN',
    'IQ': 'IRQ',
    'IE': 'IRL',
    'IM': 'IMN',
    'IL': 'ISR',
    'IT': 'ITA',
    'JM': 'JAM',
    'JP': 'JPN',
    'JE': 'JEY',
    'JO': 'JOR',
    'KZ': 'KAZ',
    'KE': 'KEN',
    'KI': 'KIR',
    'KP': 'PRK',
    'KR': 'KOR',
    'KW': 'KWT',
    'KG': 'KGZ',
    'LA': 'LAO',
    'LV': 'LVA',
    'LB': 'LBN',
    'LS': 'LSO',
    'LR': 'LBR',
    'LY': 'LBY',
    'LI': 'LIE',
    'LT': 'LTU',
    'LU': 'LUX',
    'MO': 'MAC',
    'MK': 'MKD',
    'MG': 'MDG',
    'MW': 'MWI',
    'MY': 'MYS',
    'MV': 'MDV',
    'ML': 'MLI',
    'MT': 'MLT',
    'MH': 'MHL',
    'MQ': 'MTQ',
    'MR': 'MRT',
    'MU': 'MUS',
    'YT': 'MYT',
    'MX': 'MEX',
    'FM': 'FSM',
    'MD': 'MDA',
    'MC': 'MCO',
    'MN': 'MNG',
    'ME': 'MNE',
    'MS': 'MSR',
    'MA': 'MAR',
    'MZ': 'MOZ',
    'MM': 'MMR',
    'NA': 'NAM',
    'NR': 'NRU',
    'NP': 'NPL',
    'NL': 'NLD',
    'AN': 'ANT',
    'NC': 'NCL',
    'NZ': 'NZL',
    'NI': 'NIC',
    'NE': 'NER',
    'NG': 'NGA',
    'NU': 'NIU',
    'NF': 'NFK',
    'MP': 'MNP',
    'NO': 'NOR',
    'OM': 'OMN',
    'PK': 'PAK',
    'PW': 'PLW',
    'PS': 'PSE',
    'PA': 'PAN',
    'PG': 'PNG',
    'PY': 'PRY',
    'PE': 'PER',
    'PH': 'PHL',
    'PN': 'PCN',
    'PL': 'POL',
    'PT': 'PRT',
    'PR': 'PRI',
    'QA': 'QAT',
    'RE': 'REU',
    'RO': 'ROU',
    'RU': 'RUS',
    'RW': 'RWA',
    'BL': 'BLM',
    'SH': 'SHN',
    'KN': 'KNA',
    'LC': 'LCA',
    'MF': 'MAF',
    'PM': 'SPM',
    'VC': 'VCT',
    'WS': 'WSM',
    'SM': 'SMR',
    'ST': 'STP',
    'SA': 'SAU',
    'SN': 'SEN',
    'RS': 'SRB',
    'SC': 'SYC',
    'SL': 'SLE',
    'SG': 'SGP',
    'SK': 'SVK',
    'SI': 'SVN',
    'SB': 'SLB',
    'SO': 'SOM',
    'ZA': 'ZAF',
    'GS': 'SGS',
    'ES': 'ESP',
    'LK': 'LKA',
    'SD': 'SDN',
    'SR': 'SUR',
    'SJ': 'SJM',
    'SZ': 'SWZ',
    'SE': 'SWE',
    'CH': 'CHE',
    'SY': 'SYR',
    'TW': 'TWN',
    'TJ': 'TJK',
    'TZ': 'TZA',
    'TH': 'THA',
    'TL': 'TLS',
    'TG': 'TGO',
    'TK': 'TKL',
    'TO': 'TON',
    'TT': 'TTO',
    'TN': 'TUN',
    'TR': 'TUR',
    'TM': 'TKM',
    'TC': 'TCA',
    'TV': 'TUV',
    'UG': 'UGA',
    'UA': 'UKR',
    'AE': 'ARE',
    'GB': 'GBR',
    'US': 'USA',
    'UM': 'UMI',
    'UY': 'URY',
    'UZ': 'UZB',
    'VU': 'VUT',
    'VE': 'VEN',
    'VN': 'VNM',
    'VG': 'VGB',
    'VI': 'VIR',
    'WF': 'WLF',
    'EH': 'ESH',
    'YE': 'YEM',
    'ZM': 'ZMB',
    'ZW': 'ZWE'
}

if __name__ == "__main__":
    print(TABLE_ATTRIBUTES["base"])
